export const faqs = [
  { question: "What does an AI business audit involve?", answer: "Usually one or two weeks. We talk to a few people, look at the tools you use and what slows people down, and then give you a written list of ideas ranked by how much they'd help and what they'd cost. It's yours to keep, even if you build it with someone else." },
  { question: "Will a chatbot annoy our customers?", answer: "Not if it's done properly. Ours only answer from your own information, say so when they don't know, and use a human-in-the-loop handover to pass anything tricky to a person. In addition, we test them on real questions before they go live." },
  { question: "What happens to our data?", answer: "We build on your own accounts with large language model (LLM) providers like OpenAI, Anthropic or Google, so your data stays under your control. We set things up with UK GDPR in mind. For example, we can keep everything inside your own cloud if you need that." },
  { question: "What makes a website AI-friendly?", answer: "It's fast, the content is clearly structured, and there's structured data and schema markup underneath, so AI tools can read it and describe you accurately. It's also built so that adding a chatbot or booking assistant later is simple." },
  { question: "How long does a project take?", answer: "An audit takes one to two weeks. A chatbot or automation is usually live in three to six weeks, and a new website in six to ten. We'll give you a proper timeline after the first call." },
  { question: "How much does it cost?", answer: "It depends on the size of the job. However, after the audit you get a rough cost against each idea, so you can decide what's worth doing before committing to a build." },
  { question: "Do we need technical staff to use what you build?", answer: "No. We set everything up so your team can use it day to day without any coding, and we train them before we hand over. If something needs changing later, we can do it or show you how." },
  { question: "Will AI replace people on our team?", answer: "That's not what we build for. Our tools take on the repetitive parts of the job so your people have more time for customers and the work that needs judgement. A person stays in charge of every tool." },
  { question: "What happens after launch?", answer: "We keep an eye on how things are working and tune them each month as part of ongoing optimisation. Or you can take it in-house: the accounts and code are yours." },
  { question: "What are AEO and GEO?", answer: "Ways of getting your business mentioned when people ask AI tools for recommendations. AEO is about making your own pages easy to quote. GEO is about the reviews, listings and articles elsewhere that AI models learn from." },
  { question: "Do you work with businesses outside the UK?", answer: "Yes. We're based in London but work with clients across Europe too, including several in Greece. Everything runs remotely, and we build multilingual sites and assistants in English, French and German." },
];
